var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_bone
var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_bone
var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_foot
var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_hand
var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_head
var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_hat
var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_coat
var part = instance_create_layer(x,y,"Instances",obj_part)
part.sprite_index = spr_captain_pants_air